language: ruby
cache:
  bundler: true
  directories:
  - node_modules
rvm:
- 2.3.0 
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  ssh_known_hosts:
  - 104.225.220.86
  - 104.225.220.86:8028
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_32ec88e6f89f_key -iv $encrypted_32ec88e6f89f_iv -in deploy-key.enc -out deploy-key -d
- bundle install
- nvm install 10.0.0
- nvm use 10.0.0
- npm install grunt-cli -g
- npm install
- bash _scripts/install.sh
before_script:
- echo -e "Host 104.225.220.86\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- echo -e "Host 104.225.220.86:8028\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- bash _scripts/build.sh
after_success:
- bash _scripts/deploy.sh
notifications:
  slack: snarc:Gg5ax4SydLjIhkl9IU3N4V29

